{block #content}

<h2>Archives</h2>


<table id="posts-table">
	<tr>
		<th>Posts</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>
	
	{foreach $posts as $post}		
	<tr>
		<td class="title" title="{!$post->body|striptags|truncate:200}">
			{*<a href="{plink Posts:post, $post->url}">*}
				{$post->title}
			{*</a> *}
		</td>
		<td class="time">
			{$post->date|date}
		</td>
		<td class="edit">
			<a class="edit-link" href="{plink AdminPosts:editpost, $post->id}">Edit</a>
		</td>
		<td class="delete">	
			<a class="delete-link" href="{plink AdminPosts:deletepost, $post->id}">Delete</a>
		</td>
	</tr>
	{/foreach}	
</table> 


<table id="beeps-table">
	<tr>
		<th>Beeps</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>
	
	{foreach $beeps as $beep}
	<tr>
		<td class="title">
			{!$beep->beep|striptags|truncate:100}
		</td>
		<td class="time">
			{$post->date|date}
		</td>
		<td class="edit">
			<a class="edit-link" href="{plink AdminPosts:editbeep, $beep->id}">Edit</a>
		</td>
		<td class="delete">	
			<a class="delete-link" href="{plink AdminPosts:deletebeep, $beep->id}">Delete</a>
		</td>
	</tr>
	{/foreach}	
</table> 


<div class="cleaner"></div>
