
{block content}

	<div class="post">

		<h1 class="title">{$post->title} {if $post->state == 3}<span class="draft-sign">Draft</span>{/if}</h1>

		{if isset($logged_user)}
			{if ($logged_user['role']== 'admin')}
				<p><a href="{plink AdminPosts:editpost, $post->id}">Edit</a> | <a href="{plink Auth:logout}">Logout</a></p>
			{/if}
		{/if}	

		{!$post->body|texy}

		<p class="info">
			{!$post->date|timeAgoInWords} napsal {$post->realname}

			{var $tags = $presenter->processPostTags($post->tags)}
			{if ($tags)}					
				|
				<span class="tags">
					tagy:
					{foreach $tags as $tag => $tag_url}
						<a href="{plink Posts:tag, $tag_url}">{$tag}</a>
					{/foreach}
				</span>
			{/if}
            
            {if ($settings['comments_enabled']) == 1 AND (!$post->comments_disabled) AND ($post['state'] != 3)}
                | <a href="#comments">Komentáře: {$post->comments_count}</a>
            {/if}
		</p>

	</div>



{if ($settings['comments_enabled']) == 1 AND (!$post->comments_disabled) AND ($post['state'] != 3)}

    <div id="comments">

        <h2 id="comments-heading">Komentáře</h2>
        {if count($comments) > 0}
            {foreach $comments as $comment}
                <div id="comment{$comment->id}" class="comment depth-{$comment->depth}">
                    <p class="info">
                        <span class="author"><b>{$comment->author}</b></span>
                        <span class="time">{$comment->time|timeAgoInWords}</span>
                        <a href="#frm-commentForm" onclick="document.getElementById('frmcommentForm-parent_id').value = '{!$comment->id}'; location.href = '#frm-commentForm'; return false;">Reagovat</a>
                    </p>

                    <div class="body">{!$comment->body|texy}</div>
                </div>
            {/foreach}
        {else}
            <p>Zatím žádné komentáře.</p>
        {/if}

        
    	<h2 id="comment-form-heading">Přidat komentář</h2>
	    	<ul id="comment-help">
	    		<li>Můžete použít <a href="http://texy.info/cs/syntax">Texy syntaxi</a>, HTML není povoleno</li>
	    		<li>Například: *<em>kurzíva</em>*, **<b>tučně</b>**, "text odkazu":adresa</li>
	    	</ul>
        	{widget commentForm}

        

		<p class="toplink"><a href="#post-main">Nahoru</a> &uarr;</p>

		<div class="cleaner"></div>

    </div>


{/if}


