
{block content}

	<div class="post">

		<h1 class="title">{$post->title} {if $post->state == 3}<span class="draft-sign">Draft</span>{/if}</h1>

		{if isset($logged_user)}
			{if ($logged_user['role']== 'admin')}
				<p><a href="{plink AdminPosts:editpost, $post->id}">Edit</a> | <a href="{plink Auth:logout}">Logout</a></p>
			{/if}
		{/if}	

		{!$post->perex|texy}

		{!$post->body|texy}

		<p class="info">
			{!$post->date|timeAgoInWords} napsal {$post->realname}

			{var $tags = $presenter->processPostTags($post->tags)}
			{if ($tags)}					
				|
				<span class="tags">
					tagy:
					{foreach $tags as $tag => $tag_url}
						<a href="{plink Posts:tag, $tag_url}">{$tag}</a>
					{/foreach}
				</span>
			{/if}
            
            {if ($settings['comments_enabled']) == 1 AND (!$post->comments_disabled) AND ($post['state'] != 3)}
                | <a href="#comments">Komentáře: {$post->comments_count}</a>
            {/if}
		</p>

	</div>



{if ($settings['comments_enabled']) == 1 AND (!$post->comments_disabled) AND ($post['state'] != 3)}

    <div id="comments">

        <h3>Komentáře</h3>
        {if count($comments) > 0}
            {foreach $comments as $comment}
                <div id="comment{$comment->id}" class="comment">
                    <p class="info">
                        <span class="author"><b>{$comment->author}</b></span>
                        <span class="time">{$comment->time|timeAgoInWords}</span>
                    </p>

                    <div class="body">{!$comment->body|texy}</div>                
                </div>
            {/foreach}
        {else}
            <p>Zatím žádné komentáře.</p>
        {/if}

    </div>

    <h3>Přidat komentář</h3>
        {widget commentForm}

{/if}
