{block #content}

<h2>Users</h2>	

<table id="users-table">
	<tr>
		<th>Users</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>		
	</tr>
	
	{foreach $registered_users as $registered_user}
	<tr class="{if $logged_user['id'] == $registered_user['id']}logged{/if}{if !$registered_user->password}invited{/if}">
		<td class="realname">
			{if !$registered_user->password}
				<span class="invited-sign">Invited</span>
			{/if}
			{$registered_user->realname}
		</td>
		<td class="email">
			{$registered_user->email}
		</td>
		<td class="about">
			{$registered_user->about|truncate:100|}
		</td>
		{if $logged_user['id'] == $registered_user['id']}
			<td class="edit">
				<a class="edit-link" href="{plink AdminUsers:edituser, $registered_user['id']}">Edit</a>
			</td>
		{else}
			<td></td>
		{/if}
	</tr>
	{/foreach}	
</table> 
	
<div class="cleaner"></div>

<h3>Invite new user</h3>
	{widget inviteUserForm}

<h3>Add new user</h3>
	<p><a href="{plink AdminUsers:adduser}">Add user</a></p>



