{block #content}

{*<h2>Archives</h2>*}

<div id="tabs">

	<ul>
		<li><a href="#posts">Posts</a></li>
		<li><a href="#comments">Comments</a></li>
		<li><a href="#tags">Tags</a></li>
	</ul>

	<div id="posts">
		{snippet}
			<table id="posts-table">
				<tr>
					<th>Posts</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>

				{foreach $posts as $post}
				<tr>
					<td class="title {if($post->state) == 3}draft-post{/if}" title="{!$post->body|striptags|truncate:200}">
						{if($post->state) == 3}
							<span class="draft-sign">Draft</span>
						{/if}

						<a href="{plink Posts:post, $post->url}">
							{$post->title}
						</a> 
					</td>
					<td class="time">
						{$post->date|date}
					</td>
					<td class="edit">
						<a class="edit-link" href="{plink AdminPosts:editpost, $post->id}">Edit</a>
					</td>
					<td class="delete">
						<a class="delete-link" href="{plink AdminPosts:deletepost, $post->id}">Delete</a>
					</td>
				</tr>
				{/foreach}

			</table>
			{control vp}
		{/snippet}
	</div>


	<div id="comments">
		<table id="comments-table">
			<tr>
				<th>Comments</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>

			{foreach $comments as $comment}
			<tr>
				<td class="">
					{$comment->time|timeAgoInWords} {$comment->author}
				</td>
				<td class="" title="{$comment->body}">
					<a href="{plink Posts:post, $comment->post_url}#comment{$comment->id}">{!$comment->body|truncate:100|texy}</a>
				</td>
				{*
				<td class="edit">
					<a class="edit-link" href="{plink AdminPosts:editcomment, $comment->id}">Edit</a>
				</td>
				*}
				<td class="delete">
					<a class="delete-link" href="{link deletecomment!, $comment->id}">Delete</a>
				</td>
			</tr>
			{/foreach}
		</table>
	</div>


	<div id="tags">
		<table id="tags-table">
			<tr>
				<th>Tags</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>

			{foreach $tags as $tag}
			<tr>
				<td class="">
					{$tag->tag}
				</td>
				<td class="edit">
					<a class="edit-link" href="{plink AdminPosts:edittag, $tag->id}">Edit</a>
				</td>
				<td class="delete">
					<a class="delete-link" href="{link deletetag!, $tag->id}">Delete</a>
				</td>
			</tr>
			{/foreach}
		</table>
	</div>

</div>