{block #content}

<h2>Users</h2>	

<table id="users-table">
	<tr>
		<th>Users</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>		
	</tr>
	
	{foreach $registered_users as $registered_user}
	<tr {if $logged_user['id'] == $registered_user['id']}class="logged"{/if}>
		<td class="realname">
			{$registered_user->realname}
		</td>
		<td class="email">
			{$registered_user->email}
		</td>
		<td class="about">
			{$registered_user->about|truncate:100|}
		</td>
		{if $logged_user['id'] == $registered_user['id']}
			<td class="edit">
				<a class="edit-link" href="{plink AdminUsers:edituser, $registered_user['id']}">Edit</a>
			</td>
		{else}
			<td></td>
		{/if}
	</tr>
	{/foreach}	
</table> 
	

