{var $robots = noindex}
{block #content}

<h1>Stránka nenalezena</h1>

<p>
	Stránka kterou požadujete nebyla nalezena. Je možné, že adresa je nesprávná, nebo že stránka již neexistuje.
	Zkuste hledat na <a href="{plink Homepage:}">hlavní stránce</a>. 
</p> 

<p><small>error 404</small></p>

{*
<h1>Page Not Found</h1>

<p>The page you requested could not be found. It is possible that the address is
incorrect, or that the page no longer exists. Please use a search engine to find
what you are looking for.</p>

<p><small>error 404</small></p>
*}