
{block content}

	<div class="post">

		<h1 class="title">{$post->title} {if $post->state == 3}<span class="draft-sign">Draft</span>{/if}</h1>

		<p class="info">
			{!$post->date|timeAgoInWords} napsal {$post->realname}

			{if ($presenter->getPostTags($post->id))}
 				|
					<span class="tags">
						tagy:
						{foreach $presenter->getPostTags($post->id) as $tag}
							<a href="{plink Posts:tag, $tag->tag_url}">{$tag->tag}</a>
						{/foreach}
					</span>
			{/if}
		</p>


		{if isset($logged_user)}
			{if ($logged_user['role']== 'admin')}
				<p><a href="{plink AdminPosts:editpost, $post->id}">Edit</a> | <a href="{plink Auth:logout}">Logout</a></p>
			{/if}
		{/if}
		

		{!$post->perex|texy}

		{!$post->body|texy}

	</div>

	

