
{block content}
	
		<h1>{$post->title}</h1>

		{if isset($logged_user)}
			{if ($logged_user['role']== 'admin')}
				<p><a href="{plink AdminPosts:editpost, $post->id}">Edit</a> | <a href="{plink Auth:logout}">Logout</a></p>
			{/if}
		{/if}
		

		{!$post->perex|texy}

		{!$post->body|texy}

		<p>{!$post->date|timeAgoInWords} napsal {$post->username}</p>

		<div>
			tagy:
			{foreach $presenter->getPostTags($post->id) as $tag}
				<a href="{plink Posts:tag, $tag->tag_url}">{$tag->tag}</a>
			{/foreach}
		</div>

	

