<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{if isset($post->lang)}
	{if $post->lang == 1}
		{var $lang = "cs"}
	{else}
		{var $lang = "en"}
	{/if}
{else}
	{var $lang = "cs"}
{/if}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{$lang}" lang="{$lang}">	
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="
		{if isset($post->meta_description)}
			{$post->meta_description}
		{else}
			{$settings['meta_description']}
		{/if}
	">
	<meta name="keywords" content="
		{if isset($post->meta_keywords)}
			{$post->meta_keywords}
		{else}
			{$settings['meta_keywords']}		
		{/if}
	">

	<meta http-equiv="Content-Language" content="{$lang}" />

	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>
		{if isset($post->title)}{$post->title} - {/if}
		{if isset($tag->tag)}{$tag->tag} - {/if}
		{$settings["web_name"]}
	</title>

	<link rel="icon" type="image/x-icon" href="http://www.write.cz/favicon.ico"/>
	<link rel="shortcut icon" type="image/x-icon" href="http://www.write.cz/favicon.ico"/>

	<link rel="alternate" type="application/rss+xml" title="RSS" href="{plink Feed:}" />	

	<link rel="stylesheet" media="screen and (min-width: 540px)" href="{$basePath}/css/write.css" type="text/css">
	<!--[if lte IE 8]>
		<link rel="stylesheet" media="screen" href="{$basePath}/css/write.css" type="text/css" />
	<![endif]-->
	<link rel="stylesheet" media="screen and (max-width: 540px)" href="{$basePath}/css/mobile.css" type="text/css" />
	<link rel="stylesheet" media="screen" href="{$basePath}/css/COHEN_style.css" type="text/css" />
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
	
	<script type="text/javascript" src="{$basePath}/js/jquery-1.4.2.min.js"></script>

	<!--[if lt IE 7]>
		<script src="{$basePath}/script/DD_belatedPNG_0.0.8a.js" type="text/javascript"> </script>
		<script>  
	    	DD_belatedPNG.fix('.pngfix');
	    </script>
	<![endif]-->


		<script type="text/javascript">

			$(document).ready(function(){

				$("pre").hover(function() {
					var codeInnerWidth = $("code", this).width() + 10;
					if (codeInnerWidth > 720) {
						$(this).stop(true, false).css({ zIndex:"1000",position:"relative"}).animate({ width:codeInnerWidth+"px" });
					}
				}, function() {
					$(this).stop(true, false).animate({ width:720});					
				});

			});

		</script>

</head>
<body>

	<div n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>

	<div id="pgWrap">
		<div id="layout">
			<div class="contObal">

				<div id="content" class="floatLeft">
					<div id="main">
						{include #content}
					</div>
				</div>

				<div id="sidebar" class="floatRight">
					<div id="secondary">						
						{include sidebar.phtml}
					</div>
				</div>

				<div class="cleaner"></div>

			</div>

			<div id="header" class="header-blank">
				<a id="logo" href="{$baseUri}">{$settings["web_name"]}<span></span></a>
			</div>

			<div id="footer"> 
				<p>&copy; 2011 <a href="http://www.write.cz/">Write.cz</a>, s.r.o.</p>
				<p class="rss-link"><a href="{plink Feed:}" title="RSS kanál">RSS</a></p>
				<p class="rss-link"><a href="{plink AdminPosts:newpost}" title="Post">Post!</a></p>
			</div>

		</div>
	</div>


</body>
</html>
