<!DOCTYPE>
{if isset($post->lang)}
	{if $post->lang == 1}
		{var $lang = "cs"}
	{else}
		{var $lang = "en"}
	{/if}
{else}
	{var $lang = "cs"}
{/if}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{$lang}" lang="{$lang}">	
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="
		{if isset($post->meta_description)}
			{$post->meta_description}
		{else}
			{$settings['meta_description']}
		{/if}
	">
	<meta name="keywords" content="
		{if isset($post->meta_keywords)}
			{$post->meta_keywords}
		{else}
			{$settings['meta_keywords']}		
		{/if}
	">

	<meta http-equiv="Content-Language" content="{$lang}" />

	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>
		{if isset($post->title)}{$post->title} - {/if}
		{if isset($tag->tag)}{$tag->tag} - {/if}
		{$settings["web_name"]}
	</title>

	{*
		<link rel="icon" type="image/x-icon" href="http://www.write.cz/favicon.ico"/>
		<link rel="shortcut icon" type="image/x-icon" href="http://www.write.cz/favicon.ico"/>
	*}

	<link rel="alternate" type="application/rss+xml" title="RSS" href="{plink Feed:}" />	

	<link rel="stylesheet" media="screen" href="{$basePath}/css/blueprint.css" type="text/css">
	<link rel="stylesheet" media="screen and (min-width: 540px)" href="{$basePath}/css/screen.css" type="text/css">	
	<link rel="stylesheet" media="screen and (max-width: 540px)" href="{$basePath}/css/mobile.css" type="text/css" />
	<link rel="stylesheet" media="screen" href="{$basePath}/css/COHEN_style.css" type="text/css" />
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
	
	<script type="text/javascript" src="{$basePath}/js/jquery-1.5.2.min.js"></script>

		<script type="text/javascript">

			$(document).ready(function(){

				$("pre").hover(function() {
					var codeInnerWidth = $("code", this).width() + 10;
					if (codeInnerWidth > 720) {
						$(this).stop(true, false).css({ zIndex:"1000",position:"relative"}).animate({ width:codeInnerWidth+"px" });
					}
				}, function() {
					$(this).stop(true, false).animate({ width:720});					
				});

			});

		</script>

</head>
<body>

	<div n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>

	<div id="header">
		<h1><a href="{$baseUri}">{$settings["web_name"]}</a></h1>
	</div>

	


	<div id="main">
		{include #content}
	</div>    
	
	
	<div id="secondary">		
		{include sidebar.phtml}
	</div>


	<div class="cleaner"></div>




</body>
</html>
