{assign robots => noindex}

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="en" />

	{if isset($robots)}<meta name="robots" content="{$robots}">{/if}

	<title>{$title}</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/login.css" type="text/css" />	
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css" />
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon" />

</head>

<body>

	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	<div id="login">	
		<h1>Login</h1>
			<div id="login-form">
				{widget loginForm}
			</div>
			<p id="back"><a href="{$baseUri}"> &larr; Visit website</a></p>
	</div>	
	
	
</body>
</html>
	