<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Language" content="en">
    
	{if isset($robots)}<meta name="robots" content="{$robots}">{/if}

	<title>{$settings["web_name"]} admin</title>
		
	<link rel="shortcut icon" href="{$baseUri}favicon.ico" type="image/x-icon">

    <link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/blueprint.css" type="text/css">
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/admin.css" type="text/css">
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/jquery.tagsinput.css" type="text/css">
    <link rel="stylesheet" media="print" href="{$baseUri}/css/print.css" type="text/css">	

    <script type="text/javascript" src="{$basePath}/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="{$basePath}/js/jquery.autosave.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.tagsinput.js"></script>
	<script type="text/javascript" src="{$basePath}/js/netteForms.js"></script>
	<script type="text/javascript" src="{$basePath}/js/nette-ajax.js"></script>


	<script type="text/javascript">

$(document).ready(function(){

/*
   $("form").autosave({
        callbacks: {
          trigger: ["interval", function() {}]
        }      
    });
*/

	$('#frmpostForm-tags').tagsInput();

});


	</script>	

</head>
<body id="body">

	<p class="logout"><span>{$logged_user["username"]} ({$logged_user["realname"]})</span> <br> <a href="{plink Auth:logout}">Logout</a></p>

	<div id="nav" class="floating-list-menu">
		<ul>
			<li class="home-link"><a href="{plink Homepage:}">&laquo;</a></li>
			<li{ifCurrent AdminPosts:newpost} class="active"{/ifCurrent}><a href="{plink AdminPosts:newpost}">Post</a></li>			
			<li{ifCurrent AdminPosts:archives} class="active"{/ifCurrent}><a href="{plink AdminPosts:archives}">Archives</a></li>
			{*<li><a href="">Settings</a></li>*}
			<li{ifCurrent AdminUsers:} class="active"{/ifCurrent}><a href="{plink AdminUsers:}">Users</a></li>
		<ul>
		<div class="cleaner"></div>
	</div>

	<div class="cleaner"></div>

	<div id="flash-box">
		{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
	</div>
		
	<div id="admin-content">

		<div id="admin-primary">				
			{include #content}
		</div>

	</div>

	
</body>
</html>
