<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>{$settings["web_name"]}</title>

    <link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/blueprint.css" type="text/css">
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">

    <script type="text/javascript" src="{$basePath}/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/netteForms.js"></script>
	<script type="text/javascript" src="{$basePath}/js/nette-ajax.js"></script>
	<script type="text/javascript" src="{$basePath}/js/hyperon.js"></script>


</head>

<body>

{dump $logged_user}

	<div n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>

	<h1><a href="{$baseUri}">{$settings["web_name"]}</a></h1>

	<div id="main">
		{include #content}
	</div>    
    
	<p><a href="{plink AdminPosts:newpost}">post!</a></p>

	{foreach $posts as $post}
		<h2>{$post->title}</h2>
		<p>{!$post->date|date}</p>
		{!$post->body|texy}
		
	{/foreach}

</body>
</html>
