	{foreach $posts as $post}
		<div class="post">
			
			<h2><a href="{plink Posts:post, $post->url}">{$post->title}</a></h2>

			{if isset($logged_user)}
				{if ($logged_user['role']== 'admin')}
					<p><a href="{plink AdminPosts:editpost, $post->id}">Edit</a> | <a href="{plink Auth:logout}">Logout</a></p>
				{/if}
			{/if}


			{if $post->perex}
				{!$post->perex|texy}
				<p><a href="{plink Posts:post, $post->url}">Číst více</a></p>
			{else}
				{!$post->body|texy}
			{/if}
			

			<p>{!$post->date|timeAgoInWords} napsal {$post->username}</p>
	
			<div>
				tagy:
				{foreach $presenter->getPostTags($post->id) as $tag}
					<a href="{plink Posts:tag, $tag->tag_url}">{$tag->tag}</a>
				{/foreach}
			</div>

		</div>

	{/foreach}

