	{foreach $posts as $post}
		<div class="post">
			
			<h2><a href="{plink Posts:post, $post->url}">{$post->title}</a></h2>
			{!$post->body|texy}
			<p>{!$post->date|timeAgoInWords} napsal {$post->username}</p>
	
			<div>
				tagy:
				{foreach $presenter->getPostTags($post->id) as $tag}
					<a href="{plink Posts:tag, $tag->tag_url}">{$tag->tag}</a>
				{/foreach}
			</div>

		</div>

	{/foreach}

